name: 'Configure frontend reusable action'
description: 'Configure frontend reusable action'
author: 'Gutenberg Technology'

inputs:
  path:
    description: 'Path to the file to configure'
    required: true
    default: './'
  env:
    type: string
    description: 'Environment to configure'
    required: true
    default: 'production'
  conf-source-path:
    type: string
    description: 'Environment source configuration file path'
    required: true
  conf-dest-path:
    type: string
    description: 'Environment destination configuration file path'
    required: true
  artifact-name:
    type: string
    description: 'Name of the artifact to download'


runs:
  using: 'composite'
  steps:
    - name: Chec inputs
        shell: bash
        run: |
          echo "env: $env"
          echo "conf-source-path: $conf-source-path"
          echo "conf-dest-path: $conf-dest-path"
          echo "artifact-name: $artifact-name"
        env:
          env: ${{ inputs.env }}
          conf-source-path: ${{ inputs.conf-source-path }}
          conf-dest-path: ${{ inputs.conf-dest-path }}
          artifact-name: ${{ artifact-name }}

    - name: 'check pwd & ls'
      run: pwd && ls -la
      shell: bash

    - name: Download App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-name }}-${{ inputs.env }}.tar

    - name: untar App Artifact
      run: tar -xvf ${{ inputs.artifact-name }}-${{ inputs.env }}.tar
      shell: bash

    
    - name: 'tree'
      run: pwd && tree -L 3
      shell: bash   

    # - name: Copy env config file
    #   run: cp ${{ inputs.artifact-name }}-${{ inputs.env }}/${{ inputs.conf-source-file }} {{ inputs.artifact-name }}-${{ inputs.env }}/${{ inputs.conf-dest-file }}
    #   shell: bash

    # - name: 'tree'
    #   run: pwd && tree -L 3
    #   shell: bash   

    # - name: Archive dist env
    #   run: |
    #     tar -cvf ${{ github.workspace }}/${{ inputs.artifact-name }}.tar dist/${{ inputs.artifact-name }}
    #     echo "artifact-name=${{ inputs.artifact-name }}" >> $GITHUB_OUTPUT
    #   shell: bash