name: 'Configure frontend reusable action'
description: 'Configure frontend reusable action'
author: 'Gutenberg Technology'

inputs:
  path:
    description: 'Path to the file to configure'
    required: true
    default: './'
  env:
    type: string
    description: 'Environment to configure'
    required: true
    default: 'production'
  env-file:
    type: string
    description: 'Path to the environment file'
    required: true
  artifact-name:
    type: string
    description: 'Name of the artifact to download'


runs:
  using: 'composite'
  steps:
    - name: 'Path'
      run: echo ${{ inputs.path }}
      shell: bash
    - name: 'Env'
      run: echo ${{ inputs.env }}
      shell: bash
    - name: 'Env-file'
      run: echo ${{ inputs.env-file }}
      shell: bash

    - name: 'check pwd & ls'
      run: pwd && ls -la
      shell: bash

    - name: Download App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - name: untar App Artifact
      run: tar -xvf ${{ inputs.artifact-name }}.tar
      shell: bash

    - name: Download Config files Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}-config-files -C ${{ inputs.path }}

    - name: untar Config files Artifact
      run: tar -xvf ${{ inputs.artifact-name }}-config-files.tar -C ${{ inputs.path }}/config-files
      shell: bash
   
    - name: 'check pwd & ls after untar'
      run: pwd && ls -la
      shell: bash

    - name: 'check pwd & ls after untar config files'
      run: pwd && ls -la ${{ inputs.path }}/config-files
      shell: bash